### ISSUE TITLE
下载后显示找不到插件

### ISSUE THREAD

**Issue by Death-Star-Glory** [Shadow403/nonebot_plugin_BiliRequestAll#10]
Traceback (most recent call last):
  File "D:\zm\DDBOT\AIAS\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_groupmanager'
08-29 09:30:42 [ERROR] nonebot | Failed to import "nonebot_plugin_BiliRequestAll"

**Comment by Shadow403** [comment]
已更新
