### ISSUE TITLE
发送加群请求后插件报错

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadow403/nonebot_plugin_BiliRequestAll#6]
```
01-19 04:02:10 [ERROR] nonebot | Running Matcher(type='request', module=weial_bot.plugins.nonebot_plugin_BiliRequestAll) failed.
Traceback (most recent call last):
  File "c:\weial\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\weial\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\WeiAL\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\weial\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\weial\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\weial\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\weial\python38\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "c:\weial\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "c:\weial\python38\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "c:\weial\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\weial\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\weial\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\weial\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\weial\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\weial\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\weial\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\weial\python38\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\weial\python38\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\weial\python38\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\weial\python38\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "c:\weial\python38\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\NoneBot\WeiAL-Bot\.\weial_bot\plugins\nonebot_plugin_BiliRequestAll\__init__.py", line 344, in request_fans_
    status = request(groupid, uid, getID)
  File "D:\bot\NoneBot\WeiAL-Bot\.\weial_bot\plugins\nonebot_plugin_BiliRequestAll\__init__.py", line 159, in request
    config_json = json.load(open(config_fullPath))
  File "c:\weial\python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9e in position 52: illegal multibyte sequence
```

**Comment by Shadow403** [comment]
已修复
