### ISSUE TITLE
加群通知报错

### ISSUE THREAD

**Issue by ArcPav** [Shadow403/nonebot_plugin_BiliRequestAll#9]
06-14 01:57:00 [ERROR] nonebot | Running Matcher(type='request', module=nonebot_plugin_BiliRequestAll) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\robot\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\robot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\robot\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\robot\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\robot\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\robot\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\robot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\robot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\robot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\robot\.venv\lib\site-packages\nonebot_plugin_BiliRequestAll\__init__.py", line 354, in request_fans_
    status = request(groupid, uid, getID)
  File "C:\robot\.venv\lib\site-packages\nonebot_plugin_BiliRequestAll\__init__.py", line 182, in request
    if (load_switcher_captain == 1):
UnboundLocalError: local variable 'load_switcher_captain' referenced before assignment

之前是找不到captain.json 创建了空json之后就是现在的报错
/init有概率报找不到需要多使用几次才成功
如果可以的话能放示例图吗 一开始指令输错了几十次

**Comment by Shadow403** [comment]
准备发布新版本

XD

**Comment by Shadow403** [comment]
已更新
